### ISSUE TITLE
BrowserDateTimeProvider.GetInstance fails under some circumstances

### ISSUE THREAD

**Issue by tleylan** [Blazored/Localisation#12] opened 2019-11-21 13:50 UTC
It is possible to make BrowserDateTimeProvider.GetInstance fail and the culprit seems to be the call to getTimezoneOffset. It has never done this with normal usage but I can lay out the way to do it consistently.

I started using Serilog on the client (you can follow the instructions here) https://github.com/serilog/serilog/wiki/Getting-Started And note the call to the logger made in Program.cs Log.Information("Hello, world!"); With that present the call to GetInstance (above) throws an exception. I comment that out and it works normally.

I have a work-around I wrap
timeZoneOffSet = await _jsRuntime.InvokeAsync<int>("eval", "new Date().getTimezoneOffset()");
in a try/catch and upon failure simply call it again. The second call succeeds.

I don't understand how the two could be interacting but something is up. I used your repo as is and upgraded to Core 3.1 with the same results.

**Comment by chrissainty** [comment] 2019-11-23 14:18
@tleylan Thanks for raising this and apologies for not getting to it sooner. Are you using Blazor Server by any chance? If so the issue is most likely the JS runtime hasn't been established yet the retry might just give things enough time to connect.

**Comment by tleylan** [comment] 2019-11-23 15:02
No problemo. I'm using CSB. It can be made to fail by simply calling the logger in Program Main. If I comment that out no issues. Uncommented the logging works but GetInstance fails. If I call getTimezoneOffset twice I can get the commenting and no error reported with GetInstance. Due of course to my eating the error.

I did try a couple of things like getting a JS Date variable first, etc. but they all fail which makes it seem likely it that the JS runtime isn't quite ready. Perhaps some sort of "do nothing" InvokeAsync could get the JS runtime started? I could add something externally like that which I could expect might fail sometimes. I'll give that a try.

**Comment by chrissainty** [comment] 2019-11-23 15:05
Ah OK, that's interesting. Let me know how you get on, I think you're right, it's some kind of timing issue with things booting up, I'll have a bit more a play when I get some time. Would interesting to get to the bottom of it.

**Comment by tleylan** [comment] 2019-11-24 02:13
Here is my report. I wanted to warm up the JSRuntime so I added a noop operation and that's all it takes to make it succeed.

In your index.razor page right before you call GetInstance I call my noop and it no longer fails (when I log in Program.cs).

So this:
        await JsRuntime.InvokeVoidAsync("eval", "() => {};");
        var browserDateTime = await browserDateTimeProvider.GetInstance();

This works in your solution as well as in my personal projects. Still odd but manageable.

**Comment by chrissainty** [comment] 2020-01-19 14:18
I'm having a general tidy-up of issues and looking at this I'm not sure what there is to do. So I'm going to close it for now, but please reopen if you think there is a specific action we can take with this.

**Closed as completed by chrissainty** 2020-01-19 14:18 UTC
